### ISSUE TITLE
Remove ReadableStream.prototype[Symbol.asyncIterator] polyfill

### ISSUE THREAD

**Issue by nounder** [ayame113/jsonlines#11]
On newest minor release (1.33.1), `ReadableStream.prototype[Symbol.asyncIterator]` is already implemented.

(I'm allergic to polluting global state by a library.)

**Comment by ayame113** [comment]
Thank you for your interest in this library. However, there are reasons why I don't want to remove this polyfill.

- Firefox is the only browser that supports `ReadableStream.prototype[Symbol.asyncIterator]`. According to [caniuse](https://caniuse.com/mdn-api_readablestream_--asynciterator), only 2% of users have this feature. I think the polyfill is still needed.
- If `ReadableStream.prototype[Symbol.asyncIterator]` is available it will not be polyfilled. Therefore, global variables are never overwritten in Deno.
    https://github.com/ayame113/jsonlines/blob/f8d655290a4889967aab859e61a079c89ead1a09/src/polyfill.ts#L12

This library was ported to the [Deno standard library](https://deno.land/std@0.186.0/json/mod.ts). I still maintain this library for browsers that can't directly import the Deno standard library. If you're using Deno, we recommend importing from the standard library.

```ts
import { TextLineStream } from "https://deno.land/std@0.186.0/streams/text_line_stream.ts";
import { JsonParseStream } from "https://deno.land/std@0.186.0/json/json_parse_stream.ts";

const url = "https://deno.land/std@0.186.0/json/testdata/test.jsonl";
const { body } = await fetch(url);

const readable = body!
  .pipeThrough(new TextDecoderStream())  // convert Uint8Array to string
  .pipeThrough(new TextLineStream()) // transform into a stream where each chunk is divided by a newline
  .pipeThrough(new JsonParseStream()); // parse each chunk as JSON

for await (const data of readable) {
  console.log(data);
}
```

**Comment by nounder** [comment]
Thank you for such a wide consideration. My use case was only for Deno and I have not considered other runtimes, such as Firefox.

Your std example does everything I need.

Thank you for your code and explanation!

**Comment by taras** [comment]
Hey @ayame113, thank you for creating this library. 

It would be beneficial to add https://github.com/ayame113/jsonlines/issues/11#issuecomment-1538938627 to the readme.

Thank you for your time.
